# Generated by Django 5.1.1 on 2024-09-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=60)),
                ('CourseNumber', models.IntegerField()),
                ('Instructor', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
